chanzuckerberg/napari-hub-cli

napari_hub_cli/_tests/test_preview_meta.py
napari_hub_cli/cli.py
napari_hub_cli/napari_hub_cli.py
napari_hub_cli/utils.py
setup.cfg

User can use interactive mode to print just one field at a time to improve usability

Add option for interactive preview of metadata one field at a time

---

MANIFEST.in
setup.cfg

CSVs weren't being included in package, add them to MANIFEST.in

Fix install issue with resources

---

README.md

Updated the README.MD to consider the new developments and only the information that is currently being maintained and updated.

updated readme.md with the new developments

---

README.md

Updated the Installation section for the normal user branch to consider the creation of a virtual environment, as @aranega suggested

Update Installation in README.md

---

napari_hub_cli/checklist/projectquality.py
napari_hub_cli/fs/__init__.py
napari_hub_cli/fs/condainfo.py
tests/resources/conda-infos1/setup.cfg
tests/resources/conda-infos2/setup.cfg
tests/resources/conda-infos3/setup.cfg
tests/resources/conda-infos4/setup.cfg
tests/test_conda_infos.py

Extra ctc 18

---

napari_hub_cli/checklist/metadata.py

Fixes issue with some additional data not being properly computed in the checklists

CTC-33 Fix issue with additional info base feature

---

napari_hub_cli/autofix.py
napari_hub_cli/checklist/analysis.py
napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectmetadata.py
napari_hub_cli/checklist/projectquality.py
napari_hub_cli/fs/__init__.py
napari_hub_cli/fs/additional_info.py
napari_hub_cli/fs/configfiles.py
tests/resources/pyproject.toml
tests/resources/setup2.cfg
tests/resources/setup2.py
tests/resources/setup3.py
tests/test_additional_info.py
tests/test_autofix.py
tests/test_codequality_checklist_repo2.py
tests/test_doc_checklist_faulty.py
tests/test_doc_checklist_repo2.py
tests/test_file_access.py
tests/test_remote_analysis.py

Port of the feature CTC-33 in the `extra` branch

Extra ctc 33

---

napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectquality.py
napari_hub_cli/fs/condainfo.py
tests/test_conda_infos.py

Introduces fixes for #58 in branch `extra` (based on #59)

Extra ctc 40

---

README.md
napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectmetadata.py
napari_hub_cli/checklist/projectquality.py
napari_hub_cli/dependencies_solver/checker.py
napari_hub_cli/fs/__init__.py
tests/test_autofix.py
tests/test_doc_checklist_faulty.py
tests/test_doc_checklist_repo1.py
tests/test_doc_checklist_repo2.py

Integrate CTC-39 and CTC-48 in `extra`

Extra ctc 39

---

README.md
napari_hub_cli/checklist/analysis.py
napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectquality.py
napari_hub_cli/cli.py
napari_hub_cli/dependencies_solver/checker.py
napari_hub_cli/fs/ghactions.py
tests/resources/CZI-29-small/.github/workflows/test_main.yml
tests/test_checklist.py
tests/test_ghactions.py
tests/test_solver.py

Integration of CTC-54 in `extra` (this PR is based on #79)

Extra ctc 54

---

napari_hub_cli/checklist/projectquality.py
napari_hub_cli/dependencies_solver/checker.py
napari_hub_cli/dependencies_solver/pip_patch.py
napari_hub_cli/dependencies_solver/solver.py
napari_hub_cli/dependencies_solver/utils.py
tests/test_solver.py

CTC-67 Provide a form of introspection into non-install reasons

---

napari_hub_cli/checklist/projectquality.py
napari_hub_cli/dependencies_solver/checker.py
napari_hub_cli/dependencies_solver/pip_patch.py
napari_hub_cli/dependencies_solver/solver.py
napari_hub_cli/dependencies_solver/utils.py
napari_hub_cli/fs/pythonlint.py
tests/test_pythonlint.py
tests/test_solver.py

Integrate CTC-67 in `extra` (PR based on #91)

Extra CTC-67 Provide a form of introspection into non-install reasons

---

napari_hub_cli/fs/ghactions.py
napari_hub_cli/fs/license.py
napari_hub_cli/utils.py
tests/test_doc_checklist_faulty.py
tests/test_doc_checklist_repo1.py
tests/test_doc_checklist_repo2.py
tests/test_license.py

Includes CTC-68 in `extra` (based on #89 )

Extra CTC-68 Change the github API calls to be authenticated with tokens

---

napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectquality.py

What changes with this PR
---
- Divided checklist into sections
- changed Error section to the end of the checklist
- More Details section displayed after the checklist

added sections + changed more details to the end

---

napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectmetadata.py
tests/test_doc_checklist_faulty.py
tests/test_doc_checklist_repo1.py
tests/test_doc_checklist_repo2.py
tests/test_solver.py

CTC-93 Update the metadata checklist for "Display Name"

---

napari_hub_cli/checklist/metadata.py

CTC-95 Add a warning message if running without a GitHub token

---

napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectmetadata.py
tests/test_doc_checklist_faulty.py
tests/test_doc_checklist_repo1.py
tests/test_doc_checklist_repo2.py
tests/test_solver.py

Integrate CTC-93 in `extra` (this PR is based on #96)

CTC-93 Extra

---

napari_hub_cli/checklist/metadata.py

Integration CTC-95 in `extra` (this PR is based on #97 )

CTC-95 Extra

---

napari_hub_cli/dependencies_solver/checker.py
napari_hub_cli/dependencies_solver/pip_patch.py
napari_hub_cli/dependencies_solver/solver.py

CTC-101 Fix garbage files from pip installs building up in temp dir

---

napari_hub_cli/dependencies_solver/checker.py
napari_hub_cli/dependencies_solver/pip_patch.py
napari_hub_cli/dependencies_solver/solver.py

Integrate CTC-101 in `extra` (this PR is based on #109 )

Extra CTC-101

---

napari_hub_cli/fs/patch_parso.py
napari_hub_cli/fs/pythonlint.py
setup.cfg
tests/test_pythonlint.py

CTC-86 Support running the tool with a Python version that is older than the version of the plugin python

---

napari_hub_cli/fs/patch_parso.py
napari_hub_cli/fs/pythonlint.py
setup.cfg
tests/test_pythonlint.py

Integrate CTC-86 in `extra` (this PR is based on #104)

Extra CTC-86

---

napari_hub_cli/checklist/projectquality.py
napari_hub_cli/fs/ghactions.py
napari_hub_cli/fs/pythonlint.py
napari_hub_cli/utils.py
tests/test_ghactions.py

Closes CTC-55
Adds more information in the "additional" section

CTC-55 Distinguish between failed tests per platform

---

napari_hub_cli/checklist/analysis.py
napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectquality.py
napari_hub_cli/dependencies_solver/checker.py
tests/test_solver.py

CTC-99 More user friendly way to display the install information in the CSV file

---

napari_hub_cli/checklist/analysis.py
napari_hub_cli/checklist/metadata.py
napari_hub_cli/cli.py

CTC-79 Progress bar on the check-quality command

---

napari_hub_cli/checklist/analysis.py
napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectquality.py
napari_hub_cli/cli.py
napari_hub_cli/dependencies_solver/checker.py
tests/test_solver.py

Integrate CTC-79 in `extra` (this PR is based on #117)

Extra CTC-79

---

napari_hub_cli/checklist/projectquality.py

Examples below:
- napari-zulip 
- empanada-napari

CTC-109: added c extensions section

---

napari_hub_cli/fs/__init__.py
napari_hub_cli/fs/configfiles.py
setup.cfg

CTC-108 Change way of computing version number

---

napari_hub_cli/fs/__init__.py
napari_hub_cli/fs/configfiles.py
setup.cfg

Integrates CTC-108 in `extra` (this PR is based on #124)

Extra CTC-108

---

napari_hub_cli/checklist/analysis.py
napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectquality.py

CTC-114 Add different title for the linux installation in progress bar

---

napari_hub_cli/checklist/analysis.py
napari_hub_cli/checklist/metadata.py
napari_hub_cli/checklist/projectquality.py

Integrate CTC-114 in `extra` (this PR is based on #128)

Extra CTC-114

---

codecov.yml
napari_hub_cli/dependencies_solver/pip_patch.py
tests/test_utils.py

Integrate CTC-107 in `extra` (this PR is based on #130)

Extra CTC-107

---

napari_hub_cli/dependencies_solver/checker.py
tests/test_solver.py

CTC-120 Activate all platforms by default for dependency resolution
